[build-system]
requires = [
    "cmake",
    "oldest-supported-numpy",
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel.linux]
before-all = "bash ci/ci-buildwheel-prepare-linux.sh"
