name: check-generated-docstrings
on:
    push:

jobs:
  build:
    name: check-generated-docstrings
    runs-on: ubuntu-18.04
    steps:
        - name: Fetch repository
          uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: Install packages
          run: sudo apt-get update && sudo apt-get install python3-venv && sudo apt-get install clang-6.0
        - name: check_generated_docstrings
          run: ci/check_generated_docstrings.sh
