name: docstring-check
on:
    push:

jobs:
  build:
    name: docstring-check
    runs-on: ubuntu-18.04
    steps:
        - name: Fetch repository
          uses: actions/checkout@v2.1.0
          with:
            submodules: recursive
        - name: Install packages
          run: sudo apt-get update && sudo apt-get install python3-venv clang-11
        - name: Add pybind11 tools to path
          run: echo "::set-env name=PYTHONPATH::/home/runner/work/libsonata/libsonata/python/pybind11/tools"
        - name: Check clang
          run: |
            clang --version
            dpkg -L clang-11
        - name: Check docstrings
          run: ci/check_generated_docstrings.sh
