name: run-test
on:
    push:

jobs:
    build:
        name: run-test
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Fetch repository
              run: git fetch --prune --unshallow
            - name: Get submodules
              run: git submodule update --init --force --recursive
            - name: Install packages
              run: sudo apt-get install libhdf5-dev
            - name: Build and run tests
              run: mkdir BUILD && cd BUILD && cmake -DEXTLIB_FROM_SUBMODULES=ON .. && make all && ctest --output-on-failure
