name: Build

on:
  push:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.6'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.6.4
      - name: Build wheels
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BEFORE_BUILD: "bash -x ci/prepare_for_wheel_build.sh"
          CIBW_BUILD_VERBOSITY: 2
          # Only build on Python 3.x
          CIBW_BUILD: cp36-*
          CIBW_SKIP: "*-manylinux_i686"
          CIBW_BEFORE_TEST: pip install nose
          CIBW_TEST_COMMAND: nosetests -s -v -P {project}/python/tests
        run: |
          python -m cibuildwheel --output-dir wheelhouse
