name: Build

on:
  push:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.6'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.6.4

      - name: Build wheels for linux
        if: runner.os == 'Linux'
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BEFORE_BUILD: 'yum update; yum -y install hdf5-devel;'
          CIBW_BUILD_VERBOSITY: 2
          # Only build on Python 3.x
          CIBW_BUILD: 'cp3?-*'
          CIBW_SKIP: 'cp35-* cp39-* *-manylinux_i686'
          CIBW_BEFORE_TEST: pip install nose
          CIBW_TEST_COMMAND: nosetests -s -v -P {project}/python/tests
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Build wheels for mac os
        if: runner.os == 'macOS'
        env:
          MACOSX_DEPLOYMENT_TARGET: '10.13'
          CIBW_BEFORE_BUILD: 'brew update; brew install cmake; brew install hdf5'
          CIBW_BUILD_VERBOSITY: 2
          # Only build on Python 3.x
          CIBW_BUILD: 'cp3?-*'
          CIBW_SKIP: 'cp35-* cp39-*'
          CIBW_BEFORE_TEST: pip3 install nose
          CIBW_TEST_COMMAND: nosetests -s -v -P {project}/python/tests
        run: |
          python3 -m cibuildwheel --output-dir wheelhouse
